version: "3"
services:
  sql:
    image: postgres:15-alpine
    container_name: ${DBC_NAME}
    restart: unless-stopped
    #user: 1000:1000
    environment:
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PW}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    networks:
      - bay-21-internal
  
  redis:  
    image: redis
    command: "--port ${CAC_PORT} --maxmemory ${CAC_MAXMEM} --requirepass '${CAC_PW}'"
    container_name: ${CAC_NAME}
    networks:
      - bay-21-internal

  # memcached:
  #   image: memcached:latest
  #   container_name: ${CAC_NAME}
  #   ports:
  #     - ${CAC_PORT}:11211
  #   command:
  #     - '--memory-limit=512'
  #   networks:
  #     - bay-21-internal

  shimmie:
    build:
      context: .
      dockerfile: Dockerfile
    #image: shish2k/shimmie2:latest
    container_name: ${APPC_NAME}
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=sql
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PW}
      - UPLOAD_MAX_FILESIZE=4096M
      - MAX_FILE_UPLOADS=1000

      #INSTALL_DSN: "pgsql:user=shimmie;password=shimmie;host=sql;dbname=shimmie"
    ports:
      - ${PORT}:8000
    volumes:
      - ${APP_PATH}:/app/data
      #- ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${PHP_INI}:/etc/php/8.2/cli/php.ini
    networks:
      - bay-21-internal
    links:
      - sql

volumes:
  db:
    driver: local
  app: 
    driver: local

networks:
  bay-21-internal:
    external: true
    name: bay-21-internal
    