version: "3"
services:
  sql:
    image: postgres:15-alpine
    container_name: shimmie-sql
    restart: unless-stopped
    #user: 1000:1000
    user: ${PUID}:${PGID}
    environment:
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PW}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    networks:
      - bay-21-internal
      
  shimmie:
    build:
      context: .
      dockerfile: Dockerfile
    #image: shish2k/shimmie2:latest
    user: ${PUID}:${PGID}
    container_name: shimmie
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=sql
      - POSTGRES_DB=${PSQL_DB}
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PW}
      - UPLOAD_MAX_FILESIZE=4096M

      #INSTALL_DSN: "pgsql:user=shimmie;password=shimmie;host=sql;dbname=shimmie"
    ports:
      - ${PORT}:8000
    volumes:
      - ${APP_PATH}:/app/data
      #- ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${PHP_INI}:/etc/php/8.2/cli/php.ini
    networks:
      - bay-21-internal
    links:
      - sql

volumes:
  db:
    driver: local
  app: 
    driver: local

networks:
  bay-21-internal:
    external: true
    name: bay-21-internal
